# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161025_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='newss',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
