# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170123_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider-images/', verbose_name='Изображение в слайдере')),
            ],
        ),
    ]
