# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20170220_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Изображение в слайдере', 'verbose_name_plural': 'Изображения в слайдере'},
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='slider_image',
            field=models.ImageField(upload_to='slider-images/', verbose_name='Изображение'),
        ),
    ]
