# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20170222_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Изображение в слайдере', 'verbose_name_plural': 'Изображения в слайдере'},
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='date_of_adding',
        ),
    ]
