# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImagetj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider-images/', verbose_name='Тасвир')),
                ('date_of_adding', models.DateTimeField(auto_now_add=True, verbose_name='Санаи дохилкар')),
            ],
            options={
                'verbose_name_plural': 'Тасвирҳо дар слайдер',
                'ordering': ['-date_of_adding'],
                'verbose_name': 'Тасвир дар слайдер',
            },
        ),
    ]
